kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    ng-app: nglab
  name: ngmd
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      ng-app: nglab
  template:
    metadata:
      labels:
        ng-app: nglab
    spec:
      containers:
        - name: ng-container
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP