apiVersion: v1
kind: Pod
metadata:
  name: nginxmate
  namespace: default
spec:
  containers:
    - image: nginx:latest
      name: ng1
      ports:
        - name: nginx-port
          containerPort: 80
          hostPort: 80
          protocol: TCP
    - image: nginx:latest
      name: ng2
      ports:
        - name: nginx-port
          containerPort: 80
          hostPort: 81
          protocol: TCP